mmCreateView("GraphEntry_1","View3DGL","::View3DGL_1") 

mmCreateModule("PDBLoader","::PDBLoader_1") 
mmCreateModule("MoleculeSESRenderer","::MoleculeSESRenderer_1") 

mmCreateCall("MolecularDataCall","::MoleculeSESRenderer_1::getData","::PDBLoader_1::dataout")
mmCreateCall("CallRender3DGL","::View3DGL_1::rendering","::MoleculeSESRenderer_1::rendering")

mmSetParamValue("::PDBLoader_1::pdbFilename",[=[C:/Users/asterzik/bin/megamol/data/1m40_100frames-f0.pdb]=])
mmSetParamValue("::PDBLoader_1::xtcFilename",[=[C:/Users/asterzik/bin/megamol/data/1m40_100frames.xtc]=])
mmSetParamValue("::PDBLoader_1::capFilename",[=[]=])
mmSetParamValue("::PDBLoader_1::maxFrames",[=[500]=])
mmSetParamValue("::PDBLoader_1::strideFlag",[=[true]=])
mmSetParamValue("::PDBLoader_1::solventResidues",[=[]=])
mmSetParamValue("::PDBLoader_1::calcBBoxPerFrame",[=[false]=])
mmSetParamValue("::PDBLoader_1::calculateBonds",[=[true]=])
mmSetParamValue("::PDBLoader_1::recomputeSTRIDEeachFrame",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::probeRadius",[=[1.400000]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::coloringMode0",[=[Chain]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::coloringMode1",[=[Element]=])
mmSetParamValue("::MoleculeSESRenderer_1::displayedProperty",[=[Contour]=])
mmSetParamValue("::MoleculeSESRenderer_1::curvatureMode",[=[MeanCurvature]=])
mmSetParamValue("::MoleculeSESRenderer_1::contourMode",[=[Shading]=])
mmSetParamValue("::MoleculeSESRenderer_1::blur parameter",[=[DepthSensitive]=])
mmSetParamValue("::MoleculeSESRenderer_1::ViewType",[=[minusPos]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::colorWeighting",[=[0.500000]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::minGradColor",[=[#146496]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::midGradColor",[=[#f0f0f0]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::maxGradColor",[=[#ae3b32]=])
mmSetParamValue("::MoleculeSESRenderer_1::molIdxList",[=[0]=])
mmSetParamValue("::MoleculeSESRenderer_1::color::colorTableFilename",[=[colors.txt]=])
mmSetParamValue("::MoleculeSESRenderer_1::smoothNormals",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::smoothCurvature",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::smoothPositions",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::SCRadius",[=[3]=])
mmSetParamValue("::MoleculeSESRenderer_1::SCNeighbourThreshold",[=[0.600000]=])
mmSetParamValue("::MoleculeSESRenderer_1::SCDiffThreshold",[=[0.050000]=])
mmSetParamValue("::MoleculeSESRenderer_1::SCMedianFilter",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::SCCircularNeighborhood",[=[true]=])
mmSetParamValue("::MoleculeSESRenderer_1::orthographic projection",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::testcase",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::cut off point for contours",[=[0.500000]=])
mmSetParamValue("::MoleculeSESRenderer_1::depthDiff",[=[0.300000]=])
mmSetParamValue("::MoleculeSESRenderer_1::# normal blurring iterations",[=[1.000000]=])
mmSetParamValue("::MoleculeSESRenderer_1::# position blurring iterations",[=[10.000000]=])
mmSetParamValue("::MoleculeSESRenderer_1::# curvature blurring iterations",[=[10.000000]=])
mmSetParamValue("::MoleculeSESRenderer_1::white background",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::drawSES",[=[true]=])
mmSetParamValue("::MoleculeSESRenderer_1::drawSAS",[=[false]=])
mmSetParamValue("::MoleculeSESRenderer_1::offscreenRendering",[=[false]=])
mmSetParamValue("::View3DGL_1::camstore::settings",[=[]=])
mmSetParamValue("::View3DGL_1::camstore::overrideSettings",[=[false]=])
mmSetParamValue("::View3DGL_1::camstore::autoSaveSettings",[=[false]=])
mmSetParamValue("::View3DGL_1::camstore::autoLoadSettings",[=[true]=])
mmSetParamValue("::View3DGL_1::resetViewOnBBoxChange",[=[false]=])
mmSetParamValue("::View3DGL_1::anim::play",[=[false]=])
mmSetParamValue("::View3DGL_1::anim::speed",[=[4.000000]=])
mmSetParamValue("::View3DGL_1::anim::time",[=[78.112000]=])
mmSetParamValue("::View3DGL_1::backCol",[=[#000020]=])
mmSetParamValue("::View3DGL_1::showLookAt",[=[false]=])
mmSetParamValue("::View3DGL_1::viewKey::MoveStep",[=[0.500000]=])
mmSetParamValue("::View3DGL_1::viewKey::RunFactor",[=[2.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::AngleStep",[=[90.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::FixToWorldUp",[=[true]=])
mmSetParamValue("::View3DGL_1::viewKey::MouseSensitivity",[=[3.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::RotPoint",[=[Look-At]=])
mmSetParamValue("::View3DGL_1::hookOnChange",[=[false]=])
mmSetParamValue("::View3DGL_1::cam::position",[=[14.0051069;34.2193069;-30.0137234]=])
mmSetParamValue("::View3DGL_1::cam::orientation",[=[-0.872519314;-0.223988011;-0.26455918;0.344312251]=])
mmSetParamValue("::View3DGL_1::cam::projectiontype",[=[Perspective]=])
mmSetParamValue("::View3DGL_1::cam::convergenceplane",[=[0.000000]=])
mmSetParamValue("::View3DGL_1::cam::centeroffset",[=[0;0]=])
mmSetParamValue("::View3DGL_1::cam::halfaperturedegrees",[=[15.000000]=])
mmSetParamValue("::View3DGL_1::cam::halfdisparity",[=[0.025000]=])
mmSetParamValue("::View3DGL_1::cam::ovr::up",[=[0;0;0]=])
mmSetParamValue("::View3DGL_1::cam::ovr::lookat",[=[0;0;0]=])
mmSetParamValue("::View3DGL_1::view::defaultView",[=[Front]=])
mmSetParamValue("::View3DGL_1::view::defaultOrientation",[=[Top]=])
mmSetParamValue("::View3DGL_1::view::cubeOrientation",[=[-0.872519314;-0.223988011;-0.26455918;0.344312251]=])
mmSetParamValue("::View3DGL_1::view::showViewCube",[=[false]=])

